### ISSUE TITLE
no module named 'models'

### ISSUE THREAD

**Issue by cannonli7** [pranavphoenix/WavePaint#1]
Thanks for your work. In base_loss.py, I found that in line 13 "from models.ade20k import SegmentationModule, NUM_CLASS, segm_options", here the module models is not defined, could you help me with that?

**Comment by pranavphoenix** [comment]
The underlying training code is same as that of https://github.com/advimman/lama where they have used some segmentation model trained in ADE20K for generation masks. We have not used that in our experiments, You might find it in their repo.

**Comment by cannonli7** [comment]
thanks for your reply
