### ISSUE TITLE
How come the code for Level1Waveblock hasn't been released? I wanted to reference it. Can you send it to me?

### ISSUE THREAD

**Issue by WenxuanLi-whu** [pranavphoenix/WavePaint#2]
How come the code for Level1Waveblock hasn't been released? I wanted to reference it. Can you send it to me?

**Comment by pranavphoenix** [comment]
The code for Level1Waveblock comes from WaveMix code and is available here https://github.com/pranavphoenix/WaveMix/blob/main/wavemix/__init__.py

**Comment by WenxuanLi-whu** [comment]
Thanks
