### ISSUE TITLE
How do I calculate params and flops of this model ?

### ISSUE THREAD

**Issue by lijun2005** [pranavphoenix/WavePaint#4]
Hello, Could you please tell me how to calculate params and flops of this model ? I have tried thop ,like this.
```python 
flops,params = thop.profile(generator,inputs=(x1,))
print('flops: ', flops, 'params: ', params)
print('flops: %.2f M, params: %.2f M' % (flops / 1000000.0, params / 1000000.0))
```
But it seems that params and flops calculated by thop are too big.

**Comment by pranavphoenix** [comment]
you can use torchinfo library for that

**Comment by lijun2005** [comment]
Could you  please show an example?
