### ISSUE TITLE
Why does LPIPS shrink and only save one model

### ISSUE THREAD

**Issue by zztzztzztzzt** [pranavphoenix/WavePaint#7]
if prev_loss >= Final_losses["LPIPS"]:
            torch.save(model.state_dict(), PATH)
            prev_loss = Final_losses["LPIPS"]
            print("saving chkpoint")
            counter = 0

**Comment by pranavphoenix** [comment]
lower lpips is better.
it doesnt save one model, it overwrites the saved model when lpisis is lowered
